# Generated by Django 3.1.1 on 2020-09-21 15:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MainDomain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=24, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Prefecture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='SubDomain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=24, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='CompanySheet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_id', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=120)),
                ('year_founded', models.DateField(null=True)),
                ('capital', models.IntegerField(null=True)),
                ('revenue', models.IntegerField(null=True)),
                ('employee', models.IntegerField(null=True)),
                ('ave_age', models.FloatField(null=True)),
                ('grad_hire_last_year', models.IntegerField(null=True)),
                ('working_time_start', models.TimeField(null=True)),
                ('working_time_end', models.TimeField(null=True)),
                ('salary', models.IntegerField(null=True)),
                ('benefit', models.CharField(max_length=1000, null=True)),
                ('motto', models.CharField(max_length=1000, null=True)),
                ('business', models.CharField(max_length=1000, null=True)),
                ('strength', models.CharField(blank=True, max_length=1000)),
                ('weakness', models.CharField(blank=True, max_length=1000)),
                ('interested', models.CharField(blank=True, max_length=1000)),
                ('impression', models.CharField(blank=True, max_length=1000)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_sheet', to=settings.AUTH_USER_MODEL)),
                ('main_domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cs_main_domain', to='core.maindomain')),
                ('prefectures', models.ManyToManyField(related_name='cs_companies', to='core.Prefecture')),
                ('sub_domain', models.ManyToManyField(related_name='cs_sub_domain', to='core.SubDomain')),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('company_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('year_founded', models.DateField(null=True)),
                ('capital', models.CharField(max_length=100, null=True)),
                ('revenue', models.CharField(max_length=100, null=True)),
                ('employee', models.CharField(max_length=100, null=True)),
                ('ave_age', models.CharField(max_length=100, null=True)),
                ('grad_hire_last_year', models.CharField(max_length=100, null=True)),
                ('offices', models.CharField(max_length=1000, null=True)),
                ('working_time', models.CharField(max_length=100, null=True)),
                ('salary', models.CharField(max_length=100, null=True)),
                ('benefit', models.CharField(max_length=1000, null=True)),
                ('motto', models.CharField(max_length=1000, null=True)),
                ('business', models.CharField(max_length=1000, null=True)),
                ('main_domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='main_domain', to='core.maindomain')),
                ('prefectures', models.ManyToManyField(related_name='companies', to='core.Prefecture')),
                ('sub_domain', models.ManyToManyField(related_name='sub_domain', to='core.SubDomain')),
            ],
        ),
    ]
